version: "3.1"
services:
  api:
    image: miacastroco/apigateway
    restart: always
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - JWT_KEY=UniversidadNacionaldeColombia
